# Encoding

## OneHotEncoding

In [1]:
import numpy as np 
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [60]:
df=pd.read_csv("loan.csv")

In [61]:
df.head()

Loan_ID Gender Married Dependents     Education Self_Employed  \
0  LP001002   Male      No          0      Graduate            No   
1  LP001003   Male     Yes          1      Graduate            No   
2  LP001005   Male     Yes          0      Graduate           Yes   
3  LP001006   Male     Yes          0  Not Graduate            No   
4  LP001008   Male      No          0      Graduate            No   

   ApplicantIncome  CoapplicantIncome  LoanAmount  Loan_Amount_Term  \
0             5849                0.0         NaN             360.0   
1             4583             1508.0       128.0             360.0   
2             3000                0.0        66.0             360.0   
3             2583             2358.0       120.0             360.0   
4             6000                0.0       141.0             360.0   

   Credit_History Property_Area Loan_Status  
0             1.0         Urban           Y  
1             1.0         Rural           N  
2             1.0         Urban           Y  
3             1.0         Urban           Y  
4             1.0         Urban           Y

In [5]:
df.isnull().sum()

Loan_ID               0
Gender               13
Married               3
Dependents           15
Education             0
Self_Employed        32
ApplicantIncome       0
CoapplicantIncome     0
LoanAmount           22
Loan_Amount_Term     14
Credit_History       50
Property_Area         0
Loan_Status           0
dtype: int64

In [6]:
df["Gender"].mode()[0]

'Male'

In [7]:
df["Married"].mode()[0]

'Yes'

In [8]:
df["Gender"].fillna(df["Gender"].mode()[0],inplace=True)

C:\Users\ASUS\AppData\Local\Temp\ipykernel_22280\1219453514.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["Gender"].fillna(df["Gender"].mode()[0],inplace=True)


In [9]:
df["Married"].fillna(df["Married"].mode()[0],inplace=True)

C:\Users\ASUS\AppData\Local\Temp\ipykernel_22280\134601816.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["Married"].fillna(df["Married"].mode()[0],inplace=True)


In [10]:
df.isnull().sum()

Loan_ID               0
Gender                0
Married               0
Dependents           15
Education             0
Self_Employed        32
ApplicantIncome       0
CoapplicantIncome     0
LoanAmount           22
Loan_Amount_Term     14
Credit_History       50
Property_Area         0
Loan_Status           0
dtype: int64

In [11]:
endata=df[["Gender","Married"]]

In [12]:
endata

Gender Married
0      Male      No
1      Male     Yes
2      Male     Yes
3      Male     Yes
4      Male      No
..      ...     ...
609  Female      No
610    Male     Yes
611    Male     Yes
612    Male     Yes
613  Female      No

[614 rows x 2 columns]

In [14]:
pd.get_dummies(endata)

Gender_Female  Gender_Male  Married_No  Married_Yes
0            False         True        True        False
1            False         True       False         True
2            False         True       False         True
3            False         True       False         True
4            False         True        True        False
..             ...          ...         ...          ...
609           True        False        True        False
610          False         True       False         True
611          False         True       False         True
612          False         True       False         True
613           True        False        True        False

[614 rows x 4 columns]

In [16]:
pd.get_dummies(endata).info() # these are boolean type , convert to numerical

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 614 entries, 0 to 613
Data columns (total 4 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Gender_Female  614 non-null    bool 
 1   Gender_Male    614 non-null    bool 
 2   Married_No     614 non-null    bool 
 3   Married_Yes    614 non-null    bool 
dtypes: bool(4)
memory usage: 2.5 KB


In [17]:
from sklearn.preprocessing import OneHotEncoder

In [21]:
ohe = OneHotEncoder()
ar=ohe.fit_transform(endata).toarray()

In [22]:
ar

array([[0., 1., 1., 0.],
       [0., 1., 0., 1.],
       [0., 1., 0., 1.],
       ...,
       [0., 1., 0., 1.],
       [0., 1., 0., 1.],
       [1., 0., 1., 0.]])

In [24]:
pd.DataFrame(ar,columns=["Gender_Female","Gender_Male","Married_No","Married_Yes"]) # it has generated 4 columns for 2 columns so reduce it

Gender_Female  Gender_Male  Married_No  Married_Yes
0              0.0          1.0         1.0          0.0
1              0.0          1.0         0.0          1.0
2              0.0          1.0         0.0          1.0
3              0.0          1.0         0.0          1.0
4              0.0          1.0         1.0          0.0
..             ...          ...         ...          ...
609            1.0          0.0         1.0          0.0
610            0.0          1.0         0.0          1.0
611            0.0          1.0         0.0          1.0
612            0.0          1.0         0.0          1.0
613            1.0          0.0         1.0          0.0

[614 rows x 4 columns]

In [28]:
ohe = OneHotEncoder(drop="first") # it removes the first column of gender and Married(Gender_female,and Married_no)
ar=ohe.fit_transform(endata).toarray()

In [29]:
ar

array([[1., 0.],
       [1., 1.],
       [1., 1.],
       ...,
       [1., 1.],
       [1., 1.],
       [0., 0.]])

In [30]:
pd.DataFrame(ar,columns=["Gender_Male","Married_Yes"]) #

Gender_Male  Married_Yes
0            1.0          0.0
1            1.0          1.0
2            1.0          1.0
3            1.0          1.0
4            1.0          0.0
..           ...          ...
609          0.0          0.0
610          1.0          1.0
611          1.0          1.0
612          1.0          1.0
613          0.0          0.0

[614 rows x 2 columns]

## Label Encoding

In [8]:
df1 = pd.DataFrame({"name":["dog","cow","cat","sham"]})

In [9]:
df1

name
0   dog
1   cow
2   cat
3  sham

In [10]:
from sklearn.preprocessing import LabelEncoder

In [12]:
le = LabelEncoder()
le.fit_transform(df1["name"])

array([2, 1, 0, 3])

In [13]:
df1["en_name"]= le.fit_transform(df1["name"])

In [14]:
df1

name  en_name
0   dog        2
1   cow        1
2   cat        0
3  sham        3

In [15]:
df.head()

Loan_ID Gender Married Dependents     Education Self_Employed  \
0  LP001002   Male      No          0      Graduate            No   
1  LP001003   Male     Yes          1      Graduate            No   
2  LP001005   Male     Yes          0      Graduate           Yes   
3  LP001006   Male     Yes          0  Not Graduate            No   
4  LP001008   Male      No          0      Graduate            No   

   ApplicantIncome  CoapplicantIncome  LoanAmount  Loan_Amount_Term  \
0             5849                0.0         NaN             360.0   
1             4583             1508.0       128.0             360.0   
2             3000                0.0        66.0             360.0   
3             2583             2358.0       120.0             360.0   
4             6000                0.0       141.0             360.0   

   Credit_History Property_Area Loan_Status  
0             1.0         Urban           Y  
1             1.0         Rural           N  
2             1.0         Urban           Y  
3             1.0         Urban           Y  
4             1.0         Urban           Y

In [21]:
df["Property_Area"].unique()  # unique values of property column

array(['Urban', 'Rural', 'Semiurban'], dtype=object)

In [19]:
le = LabelEncoder()      # fit trains the model and transform converts the categorical values to numerical values
le.fit(df["Property_Area"])

LabelEncoder()

In [22]:
df["Property_Area"]=le.transform(df["Property_Area"])

In [23]:
df["Property_Area"]

0      2
1      0
2      2
3      2
4      2
      ..
609    0
610    0
611    2
612    2
613    1
Name: Property_Area, Length: 614, dtype: int32

In [24]:
df.head(3)

Loan_ID Gender Married Dependents Education Self_Employed  \
0  LP001002   Male      No          0  Graduate            No   
1  LP001003   Male     Yes          1  Graduate            No   
2  LP001005   Male     Yes          0  Graduate           Yes   

   ApplicantIncome  CoapplicantIncome  LoanAmount  Loan_Amount_Term  \
0             5849                0.0         NaN             360.0   
1             4583             1508.0       128.0             360.0   
2             3000                0.0        66.0             360.0   

   Credit_History  Property_Area Loan_Status  
0             1.0              2           Y  
1             1.0              0           N  
2             1.0              2           Y

## OrdinalEncoder

In [49]:
# here sklearn is used for encoding

In [40]:
df2 = pd.DataFrame({"size":["s","m","s","l","l","xl","s","xl","m","s","l"]}) # here df2 is used so use df2 for analysis

In [41]:
df2

size
0     s
1     m
2     s
3     l
4     l
5    xl
6     s
7    xl
8     m
9     s
10    l

In [42]:
ord_data =[["s","m","l","xl"]]

In [43]:
from sklearn.preprocessing import OrdinalEncoder

In [44]:
oe = OrdinalEncoder(categories=ord_data)
oe.fit(df2[["size"]])

OrdinalEncoder(categories=[['s', 'm', 'l', 'xl']])

In [47]:
df2["size_en"]=oe.transform(df2[["size"]]) # we can also use df2["size"]=oe.transform(df2[["size"]]) , it will just replace values with the size ,
#size_en will not be there

In [48]:
df2

size  size_en
0     s      0.0
1     m      1.0
2     s      0.0
3     l      2.0
4     l      2.0
5    xl      3.0
6     s      0.0
7    xl      3.0
8     m      1.0
9     s      0.0
10    l      2.0

In [50]:
# now we will use map() function for ordinal encoding, the only difference between two is in map() we can give the order according to our choice

In [51]:
ord_data1={"s":5,"m":6,"l":7,"xl":8}

In [55]:
df2["map_en"] = df2["size"].map(ord_data1)

In [56]:
df2

size  size_en  map_en
0     s      0.0       5
1     m      1.0       6
2     s      0.0       5
3     l      2.0       7
4     l      2.0       7
5    xl      3.0       8
6     s      0.0       5
7    xl      3.0       8
8     m      1.0       6
9     s      0.0       5
10    l      2.0       7

In [62]:
df.head() # loan csv file

Loan_ID Gender Married Dependents     Education Self_Employed  \
0  LP001002   Male      No          0      Graduate            No   
1  LP001003   Male     Yes          1      Graduate            No   
2  LP001005   Male     Yes          0      Graduate           Yes   
3  LP001006   Male     Yes          0  Not Graduate            No   
4  LP001008   Male      No          0      Graduate            No   

   ApplicantIncome  CoapplicantIncome  LoanAmount  Loan_Amount_Term  \
0             5849                0.0         NaN             360.0   
1             4583             1508.0       128.0             360.0   
2             3000                0.0        66.0             360.0   
3             2583             2358.0       120.0             360.0   
4             6000                0.0       141.0             360.0   

   Credit_History Property_Area Loan_Status  
0             1.0         Urban           Y  
1             1.0         Rural           N  
2             1.0         Urban           Y  
3             1.0         Urban           Y  
4             1.0         Urban           Y

In [65]:
df["Property_Area"].unique() # if null values is their then first fill it , then do encoding

array(['Urban', 'Rural', 'Semiurban'], dtype=object)

In [68]:
en_ord_data=[['Rural','Semiurban','Urban']]

In [69]:
oen =OrdinalEncoder(categories=en_ord_data)

In [72]:
df["Property_Area"]=oen.fit_transform(df[["Property_Area"]])

In [73]:
df.head()

Loan_ID Gender Married Dependents     Education Self_Employed  \
0  LP001002   Male      No          0      Graduate            No   
1  LP001003   Male     Yes          1      Graduate            No   
2  LP001005   Male     Yes          0      Graduate           Yes   
3  LP001006   Male     Yes          0  Not Graduate            No   
4  LP001008   Male      No          0      Graduate            No   

   ApplicantIncome  CoapplicantIncome  LoanAmount  Loan_Amount_Term  \
0             5849                0.0         NaN             360.0   
1             4583             1508.0       128.0             360.0   
2             3000                0.0        66.0             360.0   
3             2583             2358.0       120.0             360.0   
4             6000                0.0       141.0             360.0   

   Credit_History  Property_Area Loan_Status  
0             1.0            2.0           Y  
1             1.0            0.0           N  
2             1.0            2.0           Y  
3             1.0            2.0           Y  
4             1.0            2.0           Y